/**
 *
 * @author ebrima
 * Incident IDL poc sample
 */
 
 interface Incident{
	   string get_incident_id();
	   void set_incident_id(in string incident_id);
	   
	   string get_status();
	   void set_status(in string status);
	   
	   string get_created_timestamp();
	   void set_created_timestamp(in string created_timestamp);
};

interface IncidentService{
	    ::Incident
	    create_incident(
	        in string incident_id
	    );
	    
	    ::Incident
	    find_incident(
	        in string incident_id
	    );
	    
	    void
	    remove_incident(
	        in string incident_id
	    );
};
